before_script:
 - poetry install

stages:
  - build
  - deploy

.build:
  stage: build
  except:
    - schedules

build/linux:
  extends: .build
  tags: [linux]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile gcc8-release

build/macos:
  extends: .build
  tags: [macos]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile macos-release

build/windows:
  extends: .build
  tags: [windows]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile vs2019-release


.deploy:
  stage: deploy
  except:
    - schedules
  when: manual
  only:
    - tags

deploy/linux:
  extends: .deploy
  tags: [linux]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home deploy

deploy/macos:
  extends: .deploy
  tags: [macos]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home deploy

deploy/windows:
  extends: .deploy
  tags: [windows]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home deploy

mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags only
    - master
  except:
    - schedules
  script:
    - poetry run python run-ci.py --isolate-conan-user-home mirror
